@extends(getTemplate().'.view.layout.layout')

@section('title')
    {{ !empty($setting['site']['site_title']) ? $setting['site']['site_title'] : '' }}
@endsection
@section('meta_description',get_option('site_meta_description'))
@section('meta_keyword',get_option('site_meta_keyword'))
@section('page')

    {{--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
           integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">--}}



    <div class="container py-5">
        <div class="row h-100 align-items-center py-5">
            <div class="col-lg-12">
                <h1 class="display-4 text-center p-4">Privacy Policy </h1>
                <p class=" text-muted mb-0 leading-loose">
                    Tutoring School is devoted to safeguarding your personal information. This Privacy Policy outlines
                    how Tutoring School collects, uses, and discloses your personal information.
                    This Privacy Policy applies to our website and associated subdomains as well as our Tutoring School
                    application. By accessing or using our Service, you consent to collecting, storing, using, and
                    sharing your personal information as indicated in this Privacy Policy.
                </p>
                <h3 class="mt-4 mb-4"> Terminologies</h3>
                <p class="text-justify leading-loose">
                    Every time any of these terms are cited in this Privacy Policy to explain things as simple as possible, they are strictly defined as:
                    <br>
                   <b>Cookie: </b>  A cookie is a little piece of data generated by a website and saved by your browser. It's used to recognize your browser, give analytics, and remember information about you, such as your preferred language or login credentials.  <br>
                    <b> Company:</b> When "Company," are used in this Policy, they mean to Tutoring School, which is responsible for your information under this Privacy Policy.  <br>
                    <b> Customer:</b> A company, organization, or individual who registers up to use the Tutoring School Service to manage interactions with their customers or service users is referred to as a customer.  <br>
                    <b> Device:</b> Any internet-connected device, such as a phone, tablet, computer, or another device, that can be utilized to access and use the services at Tutoring School.  <br>
                    <b> IP:</b> A number known as an Internet protocol (IP) address is assigned to every device connected to the Internet. In most cases, these numbers are assigned in geographic blocks. A device's IP address is frequently used to identify the location from which it connects to the Internet.  <br>
                    <b> Personnel:</b> Individuals hired by Tutoring School or under contract to conduct a service on behalf of one of the parties are referred to as personnel.  <br>
                    <b> Personal Data:</b> Any information that provides for the identity or identifiability of a natural person directly, indirectly, or in combination with other information.  <br>
                    <b> Service:</b> This term refers to the Tutoring School service as defined in the applicable terms and on this platform.  <br>
                     Advertisers, contest sponsors, promotional and marketing partners, and others that offer our material or whose products or services we believe may be of interest to you are referred to as third-party services.  <br>
                    <b> Website:</b> The Tutoring School's website can be found at http://tutorings.com  <br>
                    <b> User:</b> A person or entity who has signed up to use Tutoring School's services.  <br>

                </p>
            </div>
        </div>
    </div>

    <div class="container py-5">
        <div class="row h-100 align-items-center py-5">
            <div class="col-lg-6 d-none d-lg-block">
                <img src="{{asset('assets/default/images/privacy-new.jpeg')}}" alt="" class="img-fluid">
            </div>

            <div class="col-lg-6">
                <h3 class="mt-5 mb-5"> Information We Collect </h3>
                <p style="line-height: 30px">
                    We collect information from you when you visit our website, register on our site, place an order,
                    subscribe to our newsletter, respond to a survey or fill out a form.
                </p>
                <ul style="line-height: 30px;list-style: disc">
                    <li><i class="fas fa-check mr-2"></i> Contact Information</li>
                    <li><i class="fas fa-check mr-2"></i> Phone Numbers</li>
                    <li><i class="fas fa-check mr-2"></i> Name / Username</li>
                    <li><i class="fas fa-check mr-2"></i> Email addresses</li>
                    <li><i class="fas fa-check mr-2"></i> Addresses to send messages to</li>
                    <li><i class="fas fa-check mr-2"></i> Camera (Pictures): Allowing the user to immediately upload any
                        photo allows you to deny camera rights safely.
                    </li>
                    <li><i class="fas fa-check mr-2"></i> Photo Gallery (Pictures): Giving a user photo gallery access
                        allows them to submit any picture from their photo gallery; however, photo gallery permission
                        can be readily restricted for this.
                    </li>
                </ul>

            </div>

        </div>
    </div>

    <div class="container py-5">
        <div class="row h-100 align-items-center py-5">
            <div class="col-lg-12">
                <h3 class="mt-4 mb-4"> When does Tutoring School use end-user information from third parties? </h3>
                <p class="text-justify leading-loose">
                    Tutoring School will collect end User Data to provide our customers with tutoring school services.
                    End-users may voluntarily give us the information they have made available on social media networks.
                    We may collect publicly available information from the social networking websites you have
                    identified if you supply us with such information. By visiting these websites and updating your
                    privacy settings, you can manage how much your data is made public on social media networks.
                </p>

                <h3 class="mt-4 mb-4">
                    Using the Collected Data
                </h3>
                <p class="text-justify leading-loose">
                    We may use any information we obtain from you in one of the following ways:
                <ul style="line-height: 30px;list-style: disc">
                    <li><i class="fas fa-check mr-2"></i> To improve our website (your information allows us to better
                        respond to your specific needs).
                    </li>
                    <li><i class="fas fa-check mr-2"></i>To personalize your experience (we continually strive to
                        improve our website offerings based on the information and feedback we receive from you).
                    </li>
                    <li><i class="fas fa-check mr-2"></i>Enhance client service (your information helps us to more
                        effectively respond to your customer service requests and support needs).
                    </li>
                    <li><i class="fas fa-check mr-2"></i>To send periodic emails.</li>
                    <li><i class="fas fa-check mr-2"></i>To process transactions.</li>
                    <li><i class="fas fa-check mr-2"></i> To manage a contest, promotion, survey, or other site feature.
                    </li>
                </ul>
                </p>


                <h3 class="mt-4 mb-4">
                    How Do We Use Your Email Address?
                </h3>
                <p class="text-justify leading-loose">
                    You agree to receive emails from us by submitting your address on this website. You can unsubscribe
                    from any of these email lists at any time by clicking the opt-out Link or other unsubscribe options
                    contained in the relevant email.
                    Only people who have permitted us to contact them directly or through a third party receive emails
                    from us. We don't send unsolicited commercial emails because, like you, we despise spam. You agree
                    to use your email address for customer audience targeting on sites like Facebook by submitting your
                    email address. People who have opted to receive communications from us will see customized
                    advertisements. Email addresses supplied solely through the order processing page will be used for
                    the exclusive purpose of sending you order-related information and updates. We may use your email
                    for any of the purposes listed in this Policy if you have submitted it to us in another way.
                    Note: You can unsubscribe from receiving future emails at any time by following the full unsubscribe
                    instructions at the bottom of each email.

                </p>

                <h3 class="mt-4 mb-4">
                    How Long Do We Keep Your Information?
                </h3>
                <p class="text-justify leading-loos">
                    We only keep your information for as long as we need it to provide you with Tutoring School and
                    accomplish the goals outlined in this Policy. This also applies to anybody with whom we disclose
                    your information or perform services on our behalf. When we no longer need to use your information
                    and don't need to keep it to meet our legal or regulatory obligations, we'll either delete it or
                    depersonalize it so that we can't identify you.
                </p>

                <h3 class="mt-4 mb-4">
                    How Do We Protect Your Information?
                </h3>
                <p class="text-justify leading-loos">
                    When you place a purchase, enter, submit, or access your personal information, we use a variety of
                    security procedures to keep your personal data safe. We provide access to a secure server. All given
                    sensitive/credit information is encrypted and sent using Secure Socket Layer (SSL) technology to our
                    Payment gateway providers' database. It is only accessible by individuals with special access
                    privileges to such systems and who are expected to keep the information confidential. Your private
                    information (credit cards, social security numbers, financials, and so on) is never retained on file
                    after a transaction. However, we cannot guarantee the total security of any information you
                    communicate to Tutoring School, or that your information on the Service will not be accessed,
                    disclosed, altered, or deleted if any of our physical, technological, or managerial measures are
                    breached.
                </p>


                <h3 class="mt-4 mb-4">
                    Is the information collected through the Tutoring School Service secure?
                </h3>
                <p class="text-justify leading-loos">
                    We take steps to ensure the safety of your personal information. To assist safeguard, prevent
                    unauthorized access, maintain data security, and correctly use your information, we have physical,
                    electronic, and managerial measures in place. However, neither humans nor security measures,
                    including encryption technologies, are impregnable. People can also commit deliberate crimes, make
                    blunders, or fail to follow policies. As a result, while we make reasonable attempts to keep your
                    personal information secure, we cannot guarantee its complete security. If relevant legislation
                    imposes any non-disclaimable duty to protect your personal information, you agree that the basis for
                    measuring our compliance with such duty shall be willful misbehavior.
                </p>

                <h3 class="mt-4 mb-4">
                    Can I update or correct my information?
                </h3>
                <p class="text-justify leading-loos">
                    Depending on your relationship with Tutoring School, you may have the right to seek changes or
                    corrections to the information it collects. Employees may update or correct their information in
                    accordance with our company's internal employment standards.
                    Customers have the right to request that specific uses and disclosures of personally identifiable
                    information be restricted in the following ways. By canceling your account, you can
                </p>
                <ol style="line-height: 30px">
                    <li> 1) update or correct your personally identifiable information,</li>
                    <li> 2) change your preferences regarding communications and other information you receive from us, or</li>
                    <li> 3) delete the personally identifiable information we keep on our systems (subject to the following
                        paragraph).
                    </li>
                </ol>

                <p class="text-justify leading-loos">
                To safeguard your privacy and security, we may take reasonable procedures (such as demanding a unique
                password) to verify your identity before providing you profile access or making updates. You are solely
                responsible for keeping your unique password and account details secure at all times.
                You should be aware that erasing every record of the information submitted to us from our system is not
                technologically possible. Because we must back up our systems to preserve data from unintentional loss,
                a copy of your information may exist in a non-erasable format that is difficult or impossible to
                discover. All personal data held in databases we actively utilize, as well as other readily searchable
                media, will be updated, corrected, modified, or destroyed, as necessary, as soon as and to the extent
                practical and technically practicable, after receiving your request. <br>
                If you are a customer and would like to update, delete, or get any information about yourself, you can
                contact the company.
                </p>


                <h3 class="mt-4 mb-4">
                    Personnel
                </h3>
                <p class="text-justify leading-loos">
                    We collect the information you willingly offer to us if you are a Tutoring School employee or
                    applicant. We use the information we collect for HR purposes, such as administering employee
                    benefits and screening applicants. <br>
                    You can contact us to
                <ul style="line-height: 30px">
                    <li>update or amend your information,</li>
                    <li>modify your preferences for receiving communications and other information from us, or</li>
                    <li>obtain a record of the information we hold on you.</li>
                </ul>
                Other information that we store, or information that we have supplied to third parties in line with this
                Privacy Policy prior to such update, correction, change, or deletion, will be unaffected by such
                updates, corrections, changes, or deletions.
                </p>


                <h3 class="mt-4 mb-4">
                    Sale of Business
                </h3>
                <p class="text-justify leading-loos">
                    In the event of a sale, we reserve the right to transfer information to a third party. Merger or
                    other transfer of all or substantially all of Tutoring School's or any of its Corporate Affiliates'
                    (as defined herein) assets, or that portion of Tutoring School's or any of its Corporate Affiliates'
                    assets to which the Service relates, or if we cease operations or file or have filed against us a
                    petition in bankruptcy, reorganization, or similar proceeding, provided that the third party agrees
                    to abide by the terms of this Privacy Policy.
                </p>

                <h3 class="mt-4 mb-4">
                    Affiliates
                </h3>
                <p class="text-justify leading-loos">
                    Our <b> Corporate Affiliates </b> may get information (including personal information) about you.
                    "Corporate Affiliate" is defined as any person or entity that directly or indirectly controls, is
                    controlled by, or is under common control with Tutoring School, whether by ownership or otherwise,
                    for this Privacy Policy. Any information about you that we transmit to our Corporate Affiliates will
                    be treated in line with the rules of this Privacy Policy by such Corporate Affiliates.

                </p>


                <h3 class="mt-4 mb-4">
                    Governing Law
                </h3>
                <p class="text-justify leading-loos">
                    This Privacy Policy is governed by the United States of America laws, notwithstanding any conflict
                    of laws provisions. Except for those individuals who may have rights to file claims under the
                    Privacy Shield or the Swiss-US framework, you consent to the exclusive jurisdiction of the courts in
                    connection with any action or dispute arising between the parties under or in connection with this
                    Privacy Policy.
                    This Agreement and your use of the website will be governed by the laws of the United States of
                    America, excluding its conflict of laws rules. Other municipal, state, national, or international
                    laws may apply to your use of the website.
                    You signal your approval of this Privacy Policy by using Tutoring School or contacting us directly.
                    You should not interact with our website or use our services if you do not agree to this Privacy
                    Policy. Continued use of the website, direct contact with us, or acceptance of changes to this
                    Privacy Policy that do not significantly impact the use or sharing of your personal information will
                    be interpreted as acceptance of those changes.

                </p>

                <h3 class="mt-4 mb-4">
                    Your Consent
                </h3>
                <p class="text-justify leading-loos">
                    We've updated our Privacy Policy to provide you with complete transparency into what is being set
                    when you visit our site. By using our Tutoring School, registering an account, or making a purchase,
                    you hereby consent to our Privacy Policy and agree to its terms.

                </p>
                <h3 class="mt-4 mb-4">
                    Links to Other Websites
                </h3>
                <p class="text-justify leading-loos">
                    This Privacy Policy covers only the Services. The Services may contain links to other websites that
                    Tutoring School does not administer or control. We are not liable for the content, accuracy, or
                    viewpoints stated on such websites, and we do not research, monitor or review such websites for
                    correctness or completeness. Please keep in mind that our Privacy Policy is no longer in effect when
                    you click a link from the Services to another website. Any other website you visit or interact with,
                    including those that have a link on our platform, is subject to its own set of rules and policies.
                    These third parties may acquire information about you through their cookies or other ways.

                </p>
                <h3 class="mt-4 mb-4">
                    Advertising
                </h3>
                <p class="text-justify leading-loos">
                    This website may include ads from third parties and links to third-party websites. Tutoring School
                    makes no representations as to the truth or fitness of any of the material contained in those
                    advertisements or sites, and it disclaims any responsibility or liability for the conduct or content
                    of those advertisements and sites, as well as third-party offerings.
                    Tutoring School and many of the websites and services you use are free because of advertising. We
                    make every effort to ensure that our advertisements are safe, discreet, and as relevant as possible.
                    Third-party advertisements and links to other sites where goods or services are promoted do not
                    imply that Tutoring School endorses or recommends the third-party sites, goods, or services.
                    Tutoring School is not responsible for the content of any advertisements, any promises made, or the
                    quality/reliability of the items or services advertised.


                </p>
                <h3 class="mt-4 mb-4">
                    Cookies for Advertising
                </h3>
                <p class="text-justify leading-loos">
                    These cookies track your online activity on the website and other online services over time to make
                    online ads more relevant and effective for you. Interest-based advertising is the term for this type
                    of marketing. They also conduct functions such as preventing the same ad from repeating itself and
                    ensuring that advertisers display it correctly.

                </p>
                <h3 class="mt-4 mb-4">
                    Cookies
                </h3>
                <p class="text-justify leading-loos">
                    "Cookies" are used by Tutoring School to track which parts of our website you have visited. A cookie
                    is a small piece of data that your web browser saves on your computer or mobile device. Cookies are
                    used to improve the efficiency and functionality of our website, but they are not required for its
                    operation. Certain functionality, such as movies, may become unavailable without certain cookies. We
                    would not remember that you had logged in previously, so you would have to input your login details
                    every time you visited the website. The usage of cookies can be disabled in most web browsers.
                    However, if you disable Cookies, you may not be able to use some or all of the features on our
                    website. Cookies are never used to store Personally Identifiable Information.

                </p>
                <h3 class="mt-4 mb-4">
                    Cookies
                </h3>
                <p class="text-justify leading-loos">
                    "Cookies" are used by Tutoring School to track which parts of our website you have visited. A cookie
                    is a small piece of data that your web browser saves on your computer or mobile device. Cookies are
                    used to improve the efficiency and functionality of our website, but they are not required for its
                    operation. Certain functionality, such as movies, may become unavailable without certain cookies. We
                    would not remember that you had logged in previously, so you would have to input your login details
                    every time you visited the website. The usage of cookies can be disabled in most web browsers.
                    However, if you disable Cookies, you may not be able to use some or all of the features on our
                    website. Cookies are never used to store Personally Identifiable Information.

                </p>
                <h3 class="mt-4 mb-4">
                    Blocking and disabling cookies and similar technologies
                </h3>
                <p class="text-justify leading-loos">
                    You can change your browser to stop cookies and similar technologies wherever you are, but this
                    action may prevent our website from running correctly, and you may not be able to enjoy all of its
                    features and services entirely. You should also be aware that blocking cookies on your browser may
                    result in the loss of some saved information (for example, saved login details and site
                    preferences). You can use various controls depending on the browser you're using. Disabling a cookie
                    or a cookie category does not delete the cookie from your browser; you must do so from within your
                    browser; for more information, go to your browser's help menu.

                </p>
                <h3 class="mt-4 mb-4">
                    Payment Details
                </h3>
                <p class="text-justify leading-loos">
                    We guarantee that any credit card or other payment processing information you send us will be stored
                    in the most secure manner possible.
                </p>
                <h3 class="mt-4 mb-4">
                    Kids' Privacy
                </h3>
                <p class="text-justify leading-loos">
                    We gather information from children under the age of 13 to improve our services. Please notify Us if
                    You are a parent or guardian and believe Your kid has submitted Us with Personal Data without your
                    permission. If We learn that We have obtained Personal Data from anyone under the age of 13 without
                    parental consent, We will take steps to erase the data from Our servers.
                </p>
                <h3 class="mt-4 mb-4">
                    Changes To Our Privacy Policy
                </h3>
                <p class="text-justify leading-loos">
                    We may make changes to our Service and practices, which may need updates to this Privacy Policy to
                    ensure that it appropriately reflects those changes. Unless otherwise required by law, we will
                    notify you (for example, through our Service) before making changes to this Privacy Policy so that
                    you can review them before they take effect. The amended Privacy Policy will bind you if you
                    continue to use the Service. You can remove your account if you do not agree to this or any other
                    amended Privacy Policy.
                </p>
                <h3 class="mt-4 mb-4">
                    Third-Party Services
                </h3>
                <p class="text-justify leading-loos">
                    Third-party content (including data, information, applications, and other products and services) may
                    be displayed, included, or made available, and we may provide links to third-party websites or
                    services ("Third-Party Services").
                    You accept that Tutoring School is not responsible for any Third-Party Services, including their
                    accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or
                    other elements. Tutoring School does not assume and will not have any liability or duty for any
                    Third-Party Services provided to you or any other person or entity.
                    Third-Party Services and links to them are provided purely for your convenience, and you access and
                    use them at your own risk and subject to the terms and conditions of such third parties.

                </p>
                <h3 class="mt-4 mb-4">
                    Tracking Technologies
                </h3>
                <p class="text-justify leading-loos">
                <li><i class="fas fa-check mr-2"></i>Cookies</li>
                    Cookies are used to improve the efficiency and functioning of our site, but they are not required to
                    use them. However, some features, such as videos, may become inaccessible without these cookies. You
                    will be asked to enter your login information each time you visit because we will not be able to
                    remember that you have already logged in.
                <li><i class="fas fa-check mr-2"></i>Sessions</li>
                "Sessions" are used to track which parts of our website you've visited. A session is a short amount of data that your web browser saves on your computer or mobile device.
                </p>

                </p>
                <h3 class="mt-4 mb-4">
                    Contact Us
                </h3>
                <p class="text-justify leading-loos">
                    Don't hesitate to contact us if you have any questions. <br>
                    Via Email: info@tutoringschool.com <br>
                    Via this Link: http://tutorings.anabiatrading.com/
                </p>
            </div>
        </div>
    </div>



@endsection
